name: Code quality

on:
  push:
    branches: [master] # Adjust branches as needed
  pull_request:
    branches: [master] # Adjust branches as needed

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        uses: actions/checkout@v6

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci ./src
